### ISSUE TITLE
After remediation, all SSL controls are skipped

### ISSUE THREAD

**Issue by scarolan** [chef-cft/bjc#532] opened 2017-05-11 20:07 UTC
This gives the illusion of a compliant node but if you dig deeper you can see that it only passes because for some reason all the controls get skipped.

Oddly enough this behavior doesn't happen when scanning Windows 2012R2 machines.

**Comment by ChefRycar** [comment] 2017-05-15 20:33
I believe I'm familiar with the issue, and can fix. Will confirm with details shortly.

**Comment by ChefRycar** [comment] 2017-05-15 20:35
Alrighty, @modrake reported this to me as well, and I believe it to be the same issue I turned up here: https://github.com/dev-sec/ssl-baseline/issues/12

I believe using the inspec_version attribute in the audit cookbook and locking to a known good version, like 1.11.1, should do the trick. I'll do that and confirm in an environment and report back. Easy fix if so, but it'll be a dump/restore build, since it'll mean an update to bjc_bass.

**Comment by ChefRycar** [comment] 2017-05-15 21:14
Confirmed that the tests work properly if inspec is locked to version 1.19.2. 1.20.0 introduced the new ssl handshake behavior which looks like when the skips started to occur.

**Comment by ChefRycar** [comment] 2017-05-15 22:51
Moving to ready, and assigning to myself. Should be able to cut a PR tomorrow. For reference, here's the quick fix:

1) Open bjc_bass's attributes file
2) Add the following line: `default['audit']['inspec_version'] = '1.19.2'`
3) run: `knife cookbook upload bjc_bass --force'
4) run: `knife job start 'chef-client' --search '*:*'`

Should do the trick, and fix audits up.

**Closed** 2017-05-16 14:27 UTC
Labels: bug, in progress
